# Generated by Django 3.2.4 on 2021-06-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_friend_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
    ]
