# Generated by Django 3.2.4 on 2021-06-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_friend_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
